### ISSUE TITLE
Get "badrequest" when trying to get school by https://graph.microsoft.com/beta/education/schools

### ISSUE THREAD

**Issue by farawayplace613** [OfficeDev/O365-EDU-Tools#13]
Get "badrequest" when trying to get school by https://graph.microsoft.com/beta/education/schools.
The error message is "Resource not found for the segment 'education'"
![eduapiissue](https://user-images.githubusercontent.com/9522788/31323928-ee00bf5e-acdf-11e7-89b4-98b8d04d8bfd.jpg)

**Comment by AyronJohnson** [comment]
Closing issue as it is not problem with a script.  See link for connecting to this endpoint ensuring the correct scope permissions.  

https://docs.microsoft.com/en-us/graph/api/educationroot-list-schools?view=graph-rest-beta&tabs=http
