### ISSUE TITLE
validation failure when uploading CSV in SDS

### ISSUE THREAD

**Issue by tkumark** [OfficeDev/O365-EDU-Tools#33]
When I use the csv file and upload it to SDS validation fails. Do you have a working CSV file which SDS will accept.

**Comment by AyronJohnson** [comment]
Sample csv files are located here.  https://github.com/OfficeDev/O365-EDU-Tools/tree/master/CSV%20Samples

Please recreate issue and fill out the information in the issue template if the problem still exists.
