### ISSUE TITLE
Exporting OneRoster data from Blackbaud causes error

### ISSUE THREAD

**Issue by Widget985** [OfficeDev/O365-EDU-Tools#41]
I have exported my student information from our SIS (Blackbaud onCampus) in a OneRoster csv format. When I run the Convert-OneRosterToMicrosoftSDS command from the School Data Sync Toolkit in PowerShell, I get an exception
[Exception_2020-04-22_15-57-05Z.log](https://github.com/OfficeDev/O365-EDU-Tools/files/4517454/Exception_2020-04-22_15-57-05Z.log)

The specific command I am running is: `Convert-OneRosterToMicrosoftSDS -onerosterfolderpath 'C:\OneRoster\In\' -sdsfolderpath 'C:\OneRoster\Out\' -logPath 'C:\OneRoster\Logs\'
`
I've also attached the other log files, however I don't see anything in them that indicates a problem (except it says it can't find the demographics.csv file, but that is listed as optional).
[Error_2020-04-22_15-57-05Z.log](https://github.com/OfficeDev/O365-EDU-Tools/files/4517486/Error_2020-04-22_15-57-05Z.log)
[Message_2020-04-22_15-57-05Z.log](https://github.com/OfficeDev/O365-EDU-Tools/files/4517488/Message_2020-04-22_15-57-05Z.log)
[Warning_2020-04-22_15-57-05Z.log](https://github.com/OfficeDev/O365-EDU-Tools/files/4517489/Warning_2020-04-22_15-57-05Z.log)

**Comment by ewachiwa** [comment]
There is a formatting issue with one of the headers. BB includes an ‘s’ at the end of one of the headers In the classes file  (which is part of the standard) and MS barks and wants the ‘s’ removed.   After that the convert tool runs smoothly.
