### ISSUE TITLE
SDS CSV v2 Format Files Not Uploaded Here

### ISSUE THREAD

**Issue by clreinki** [OfficeDev/O365-EDU-Tools#43]
![screenshot](https://user-images.githubusercontent.com/12813987/89039077-78084700-d30f-11ea-9c76-86242aaacddc.PNG)

When attempting to create a School Data Sync v2 profile, I choose the v2 option and the link to the sample files points here - however only v1 CSV sample files are in this repo.

**Comment by gregmilligan** [comment]
Still no v2 samples.  Any timeline?  Thanks...

**Comment by clreinki** [comment]
I contacted support and they said preview files were still unavailable.  However I did find this link that detailed the specification so you can at least build your own CSV.
https://docs.microsoft.com/en-us/schooldatasync/sds-v2-csv-file-format

**Comment by BillSluss** [comment]
Sample files are now in the repo, linked here - **https://github.com/OfficeDev/O365-EDU-Tools/tree/master/CSV%20Samples/SDS%20v2**

**Comment by rdoering** [comment]
Isnt  roles.csv missing?

**Comment by AyronJohnson** [comment]
Roles not mentioned for csv v2 format https://docs.microsoft.com/en-us/schooldatasync/sds-v2-csv-file-format
