### ISSUE TITLE
unable to connect-graph issue 54264

### ISSUE THREAD

**Issue by MartyTh** [OfficeDev/O365-EDU-Tools#52]
Hello, 
         I'm new to github, I needed to run Teams script and I was stuck on connect-graph. Ther was always a timeout 120sec. I founded this after a lot a research on the web. So I want to share this info here.

https://github.com/MicrosoftDocs/azure-docs/issues/54264

this issues tell to user only powershell to get connect-graph successfully, becaus it do not work in powershel ISE.
after that, I successfully ran teams scripts.
Regards

**Comment by AyronJohnson** [comment]
Mentioned ticket is closed and issue was brought to the attention of the PowerShell ISE team
