### ISSUE TITLE
Cannot find an overload for "AcquireTokenAsync" and the argument count: "4".

### ISSUE THREAD

**Issue by markburland** [OfficeDev/O365-EDU-Tools#54]
Trying to run any of the scripts, they're all throwing up issues. get-sectionusagereport gives this error:
Cannot find an overload for "AcquireTokenAsync" and the argument count: "4".

I'm wondering if these scripts are using old versions of modules and need updating?

**Comment by AyronJohnson** [comment]
Modules should now be updated in repo
