### ISSUE TITLE
Comments in the scripts for blocking graph

### ISSUE THREAD

**Issue by Larryngolog** [OfficeDev/O365-EDU-Tools#56]
Both scripts for blocking access to graph contain reference to Powershell and not graph. For example this script https://github.com/OfficeDev/O365-EDU-Tools/blob/master/SDS%20Scripts/Block%20PowerShell/Block-MS_Graph_module_for_everyone_except_a_list_of_admins.ps1

in line 4 instead of "#set the PowerShell App ID as a variable" should be "#set the Graph App ID as a variable", correct?

**Comment by AyronJohnson** [comment]
Corrected name
