### ISSUE TITLE
Sync-GroupMembership-To-Team.ps1 giving "Team is not unlocked; only owners have been synchronized."

### ISSUE THREAD

**Issue by bmomartins** [OfficeDev/O365-EDU-Tools#57]
Hello guys,

I'm having the mentioned issue.

![image](https://user-images.githubusercontent.com/32171287/93905918-734e8680-fcf3-11ea-8fcf-a6522b4f6595.png)

Because of this, I believe, Teams cache is not updated and members (students) are unable to check their membership on their teams.

How can we fix that?

Kind regards,

**Comment by MatsAnd** [comment]
Hi @bmomartins, have you verified that the teacher have [activated their class team](https://support.microsoft.com/en-us/office/activate-early-access-class-teams-created-by-your-it-admin-0d154696-66ab-4fcf-b22f-c3d9a82aaf78?)?
