### ISSUE TITLE
How to Link Guardian Email to Student in SDS Version 2.1

### ISSUE THREAD

**Issue by naldo-gomes** [OfficeDev/O365-EDU-Tools#74]
Hello Team!
In the documentation it is not clear where the guardian email should be added to link to the student.
In version 1 of SDS, there was a "User" file where the guardian's e-mail was added. In version 2.1, there is no longer the "User" file where the link between the student and the guardian was made.
They could get me out of this doubt.

Yours sincerely,
Naldo Gomes

**Comment by AyronJohnson** [comment]
See link for Parent and Guardian CSV File Format

https://docs.microsoft.com/en-us/schooldatasync/csv-files-for-school-data-sync#parent-and-guardian-csv-file-format
